export const MAIN_WORD = 'SIHINTA'

export const WORDS = [
  'Loitta maas',
  'Maria B',
  'AirBnb \u{1F609}',
  'cutush',
  'goltush',
  'gadhu',
  'chagol',
  'motu',
  'bashay jabo',
  'matha tipe dao',
  'etta gaan shunao',
  'tolomaaa',
  'appa dao',
  'ki diba',
  'Not insinuating..',
  'hypothetically...',
  'accha dhoro',
  'thame thame',
  'sowwie',
  'free tissues',
  'Ajke Oneek Khabo',
  'Kutkut',
  'KitKat',
  'Dark',
  'Phuush',
  'Futfuti',
  'Potlaa',
  'Beyadop',
  'Buira',
  'Lalla la la la',
  'vroom vroom',
  'Bridge',
  'Dhaap',
  'How would I know..',
  'Na ekhoniii',
  'Chanachur',
  'Fuchka',
  'Busabaa',
  'Protocol',
  'Janoo ki hoise',
  'the things i do for you',
] as const
